test docker compose in CI
Signed-off-by: Boris Glimcher <Boris.Glimcher@emc.com>

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -53,3 +53,31 @@ jobs:
           labels: ${{ steps.meta.outputs.labels }}
           cache-from: type=gha
           cache-to: type=gha,mode=max
+  test:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - uses: docker/setup-qemu-action@v2
+      - uses: docker/setup-buildx-action@165fe681b849eec43aaa64d786b9ec53e690475f
+
+      - name: Start containers
+        run: docker-compose up --build --force-recreate --detach opi-test
+
+      - name: Run Tests
+        run: |
+          set -x
+          name=$(docker-compose ps | grep opi-test | awk '{print $1}')
+          rc=$(docker wait "${name}")
+          if [ "${rc}" != "0" ]; then
+              echo "opi-test failed:"
+              docker logs "${name}"
+              exit 1
+          fi
+
+      - name: Logs
+        if: always()
+        run: docker-compose logs
+
+      - name: Stop containers
+        if: always()
+        run: docker-compose down --volumes --remove-orphans
